### PR TITLE
Edited README.md

### PR DESCRIPTION
**Pull request by GenshinMinecraft**
I edited the ./README.md

### CODE REVIEW

**Comment by GenshinMinecraft** [comment]
@GenshinMinecraft who can go to merge the pr

**Comment by GenshinMinecraft** [comment]
@GenshinMinecraft byd回复都算comment

**Comment by sam13142023** [comment]
@GenshinMinecraft

**Comment by GenshinMinecraft** [comment]
@sam13142023 不是我都算啊

**Comment by GenshinMinecraft** [comment]
@GenshinMinecraft 牛逼，还能自动检测gh名字

**Review by Lemonawa — APPROVED** [review]

**Comment by GenshinMinecraft** [comment]
so，为了这该死的仪式感，谁来合了我的pr

**Review by sam13142023 — APPROVED** [review]

**Pull request merged**
